name: CI Monorepo

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install root and workspace dependencies
        run: npm install

      - name: Run ESLint across the monorepo
        run: npm run lint

      # --- Testes ---
      - name: Generate Prisma Clients for all services
        run: npm run prisma:generate:all

      - name: Run tests for all services
        run: npm run test

      # --- Build ---
      - name: Build all services
        run: npm run build
